@startuml class diagram

class Alojamiento {
    # String: nombre
    # String: direccion
    # String: localidad
    # String: gerente
}

class Hotel extends Alojamiento {
    # int: cantidadHabitaciones
    # int: cantidadCamas
    # int: cantidadPisos
    # double: precio
}

class 4Estrellas extends Hotel {
    # String: gimnasio
    # String: restaurante
    # int: capacidadRestaurante
}

class 5Estrellas extends 4Estrellas {
    - int: cantidadSalonesConferencia
    - int: cantidadSuites
    - int: cantidadLimusinas 
}

class ExtraHotel extends Alojamiento {
    # boolean: esPrivado
    # double: metrosCuadrados
}

class Camping extends ExtraHotel {
    # int: capacidadCarpas
    # int: cantidadBanios
    # boolean: tieneRestaurante
}

class Residencia extends ExtraHotel {
    # int: cantidadHabitaciones
    # boolean: tieneDescuento
    # boolean: tieneCampoDeportivo
}

@enduml