package com.egg.enums;

public enum Apellido {
    GOMEZ, GONZALEZ, LOPEZ, MARTINEZ, PEREZ, SANCHEZ, RAMIREZ, HERNANDEZ, TORRES, FERNANDEZ, NAVARRO, RUIZ, SANDOVAL,
    ROMERO, CASTILLO, MORALES, ORTIZ, MEDINA;
}
