package com.egg.enums;

public enum Nombre {
    MARINA, JUAN, DIEGO, JOSE, ROMINA, ANA, FLORENCIA, SABRINA, ALEJO, CANDELA, LUIS, ELIAS, JAVIER, LEANDRO, LEONEL, IVAN,
    SILVIA, AGOSTINA, SOLEDAD, LISANDRO, MANUEL, LUCIA, JULIAN, SIMON, NICOLE, MORENA;
}
