package com.seguros.enums;

public enum Marca {
    FIAT, TOYOTA, RENAULT, BMW, HONDA, HYUNDAI, CHEVROLET, FORD, ALFA_ROMEO, PORSCHE, PEUGEOT, CITROEN, CHERY,
    MERCEDES_BENZ, NISSAN, VOLSKWAGEN, IVECO, SCANIA, AUDI, FERRARI, KIA, OTRO;
}
